[package]
name = "discord_hub_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
log = "0.4.27"
serenity = { version = "0.12.4",features = ["default"] }
tokio = { version = "1.45.0",features = ["rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19",features = ["local-time","fmt"] }
