name: BuildFile

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: use cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: |
          cargo build --release

      - name: 'Upload build target'
        uses: actions/upload-artifact@v4
        with:
          name: discord_hub_bot
          path: |
            ./target/release/discord_hub_bot*
            !./target/release/shuba.pdb
            !./target/release/shuba.d
          retention-days: 30